### ISSUE TITLE
Support for nested(deep copy) copyWiths?

### ISSUE THREAD

**Issue by e200** [numen31337/copy_with_extension#11]
```dart
import 'package:copy_with_extension/copy_with_extension.dart';

import 'package:unig/models/client_type.dart';

part 'client.g.dart';

@CopyWith(generateCopyWithNull: true)
class Client {
  int id;

  String name;

  ClientType type;

  Client({
    this.id,
    this.name,
    this.type, // How to nest a copy to it?
  });
}
```

**Comment by e200** [comment]
`flutter pub get` and run the app again fixes it.

**Comment by e200** [comment]
But it stills being an issue, because, if I copy the Client instance, I still having the same copy of ClientType being shared by both, and if I change the ClientType name instance in one, it get updated in both, what will not always be the desired behaviour.

How we can have a new copy of the @copyWith instance that includes a new copy of all nested instances that uses @copyWith too?

**Comment by numen31337** [comment]
@e200 this is an interesting question indeed. As far as I know, this is expected behaviour and this the same pattern as Flutter use internally. The main purpose of `copyWith` function is to modify the immutable object and deep copy will introduce some performance overhead, albeit it would be nice to have both.

**Comment by e200** [comment]
> @e200 this is an interesting question indeed. As far as I know, this is expected behaviour and this the same pattern as Flutter use internally. The main purpose of `copyWith` function is to modify the immutable object and deep copy will introduce some performance overhead, albeit it would be nice to have both.

But we could make it optional 🙂

**Comment by numen31337** [comment]
Unfortunately, Dart doesn't provide us with any API to perform a deep copy. I am afraid that this logic could be rather complicated and out of the scope of this micro-library. If you have any idea on how to achieve this kind of behaviour relatively easy please let me know.

**Comment by e200** [comment]
> Unfortunately, Dart doesn't provide us with any API to perform a deep copy. I am afraid that this logic could be rather complicated and out of the scope of this micro-library. If you have any idea on how to achieve this kind of behaviour relatively easy please let me know.

json_serializable does what we want with *toJson()*.

The idea is, check if the type is not a primitive type, and if not, check if it is decorated with @copyWith and if possible, check if the type can be deeply copied...

I think you should start a RFC if you want! 😊

**Comment by numen31337** [comment]
In my opinion, such functionality is much more than the purpose of this library, because there is no easy way to achieve it. I would recommend using one of the existing libraries which already implements it as json_serializable.
