### ISSUE TITLE
[Feature Request]  null copy

### ISSUE THREAD

**Issue by sm2017** [numen31337/copy_with_extension#24]
Please add support to copy with null

**Comment by numen31337** [comment]
Hey @sm2017, isn't [this is the feature](https://pub.dev/packages/copy_with_extension_gen#additional-features) you are referring to: `copyWithNull`?

**Comment by sm2017** [comment]
@numen31337 see https://pub.dev/packages/freezed

**Comment by numen31337** [comment]
> @numen31337 see https://pub.dev/packages/freezed

I don't really get the point. Could give more context?

**Comment by sm2017** [comment]
In copyWith implementation of freezed, You can copy with null values

```dart
var person = Person('Remi', 24);

// `age` not passed, its value is preserved
print(person.copyWith(name: 'Dash')); // Person(name: Dash, age: 24)
// `age` is set to `null`
print(person.copyWith(age: null)); // Person(name: Remi, age: null)
```

In the first copyWith, we set name, and don't change age, in second we set age null and don't change other fields

Also is has a cool [deep-copy](https://pub.dev/packages/freezed#deep-copy) feature

**Comment by numen31337** [comment]
The mentioned library uses a completely different approach for generating `copyWith` function. For this library, the choice was made to have a separate `copyWithNull` function. This is by design and will not be changed at least till the introduction of non-nullable types.
