### ISSUE TITLE
Hope support no parameters constructor

### ISSUE THREAD

**Issue by scubers** [numen31337/copy_with_extension#26]
```
@CopyWith()
class User {
  String name;
  User();
}
```
this will failed.

hope support like jsonSerializable

```
extension ContactsCopyWith on Contacts {
  Contacts copyWith({
    String name,
  }) {
    return Contacts()
      ..name = name ?? this.name;
  }
}
```

**Comment by numen31337** [comment]
I afraid the provided code will not be valid anymore when nullable types will be introduced.  Perhaps I didn't understand the request correctly. If so please elaborate on this and provide more detailed description.
