### ISSUE TITLE
Add Support for Generic Types

### ISSUE THREAD

**Issue by windrunner414** [numen31337/copy_with_extension#3]
```
@CopyWith()
class A<T> {
    T a;
}
```

now generated code is
`extension ACopyWithExtension on A`
not on A<T>,but the type of field 'a' is T, it will cause a error

**Comment by windrunner414** [comment]
#4 pr here

**Comment by numen31337** [comment]
Please refer to [Add Support for Generic Types](https://github.com/numen31337/copy_with_extension/issues/5)
