### ISSUE TITLE
unsound null safety 

### ISSUE THREAD

**Issue by sm2017** [numen31337/copy_with_extension#36]
**Describe the issue**

I upgraded to flutter 2 and have to upgrade my `copy_with_extension_gen` to v2 too , the v1 has dependency conflict
My code is not sound null safety at the moment, but the generated code is sound null safety, So I have errors such as `This requires the 'non-nullable' language feature to be enabled.`
How can I generate unsound null safety codes with v2?

**Environment details**

Paste the flutter environment detail.
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.18363.1440], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (2 available)

• No issues found!

flutter --version
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (4 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2


```
Paste the package version.
```
dependencies:
  copy_with_extension: ^2.0.0
dev_dependencies:
  copy_with_extension_gen: ^2.0.1
```

**To Reproduce**

Generate code for unsound null safety application, or you can add a `--unsound-null-safety` argument

**Expected behaviour**

I must detect unsound null safety applications

**Comment by numen31337** [comment]
Unfortunately, I can not help you without the sample code that reproduces this issue. The `--unsound-null-safety` is essentially a superset of sound null safety and I really don't understand how something that is null security compliant cannot be built with this flag. Of course, I might be missing something. It is likely that you forgot need to bump the SDK version to the pubspec.

**Comment by sm2017** [comment]
My sdk version is:

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"
```


its the example 

```dart
import 'package:copy_with_extension/copy_with_extension.dart';
part 'example.g.dart';

@CopyWith()
class SimpleObject {
  final String id;
  final int value;

  SimpleObject({required this.id, required this.value});
}
```

The generated file is 

```dart
**// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'example.dart';

// **************************************************************************
// CopyWithGenerator
// **************************************************************************

extension SimpleObjectCopyWith on SimpleObject {
  SimpleObject copyWith({
    dynamic? id,
    dynamic? value,
  }) {
    return SimpleObject(
      id: id ?? this.id,
      value: value ?? this.value,
    );
  }
}

```


So I have the following error

```
This requires the 'non-nullable' language feature to be enabled.  Try updating your pubspec.yaml to set the minimum SDK constraint to 2.12.0 or higher, and running 'pub get'.
```

So I just need to remove `?` like the following

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'example.dart';

// **************************************************************************
// CopyWithGenerator
// **************************************************************************

extension SimpleObjectCopyWith on SimpleObject {
  SimpleObject copyWith({
    dynamic id,
    dynamic value,
  }) {
    return SimpleObject(
      id: id ?? this.id,
      value: value ?? this.value,
    );
  }
}

```

**Comment by numen31337** [comment]
Did you try to follow the error message and update the SDK version as I suggested?

**Comment by sm2017** [comment]
I am not ready to enable null safety in my flutter large application, it is very time consuming process, I have many nullable variable, If I  set the minimum SDK constraint to 2.12.0 or higher , I have to add `?` to all nullable variables as by default all it not null

I know that `dart migration --apply` can help, But the process it time consuming

**Comment by numen31337** [comment]
I can only suggest using the older version of the library before introducing the null-safety, namely "^1.4.0" or refer to the migration and partial migration guides for more info https://dart.dev/guides/language/evolution#per-library-language-version-selection. Unfortunately, I cannot further assist you with this topic.

**Comment by sm2017** [comment]
@numen31337 the v1 has dependency conflict, it is not possible to use both  "^1.4.0" as dependency and flutter 2

**Comment by numen31337** [comment]
@sm2017 Maybe try to override it for your specific situation https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by numen31337** [comment]
If none of the above works for you, you can always fork it, make the necessary adjustments, and use it until your project becomes 1.12 compatible.

**Comment by sm2017** [comment]
@numen31337 Thank you
