### ISSUE TITLE
Analyzer version in copy_with_extension_gen conflicts with version in json_serializable

### ISSUE THREAD

**Issue by jplekkerkerker** [numen31337/copy_with_extension#38]
Describe the issue

There is a conflict in dependencies with the newest json_serializable 5.0.0:

Because copy_with_extension_gen 2.0.2 depends on analyzer ^1.2.0 and app depends on analyzer 2.0.0, copy_with_extension_gen 2.0.2 is forbidden.
So, because app depends on copy_with_extension_gen 2.0.2, version solving failed.
pub get failed (1; So, because app depends on copy_with_extension_gen 2.0.2, version solving failed.)
Environment details

Paste the flutter environment detail.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!

Paste the package version.

dependencies:
  copy_with_extension: ^2.0.2
dev_dependencies:
  copy_with_extension_gen: ^2.0.2

Could you update the analyzer version so these packaged are compatible again?

**Comment by simonckenyon** [comment]
me to :-)
