### ISSUE TITLE
Generator does not detect private constructors

### ISSUE THREAD

**Issue by mateusfccp** [numen31337/copy_with_extension#44]
It's a very common pattern to make the default constructor private (like `MyObject._(...params)`) and provide other public constructors.

I think it would be good if the generator could detect this pattern and generate the `copyWith` method with the "unamed private constructor".

**Comment by numen31337** [comment]
I believe this specific case is mentioned in the documentation [here](https://github.com/numen31337/copy_with_extension/blob/master/copy_with_extension_gen/example/example.dart).

**Comment by mateusfccp** [comment]
You are right, I only had looked at the pub.dev page. I think we could include this there too, as it's a common case.
