### ISSUE TITLE
Include fields from parent classes in copyWith method

### ISSUE THREAD

**Issue by Wishmater** [numen31337/copy_with_extension#47]
Currently, if we have, say:

```
class A {
  String name;
  A(this.name);
}

@CopyWith
class B extends A {
  String descrip; 
  B({
    required String name
    this.descrip,
  }) : super (name);
}
```

The generated copyWith method for class B only has the "descrip" parameter, and it seems to ignore the "name" field. This is a problem in cases with big classes with lots of inheritance, or am I missing something?

If this package supports inheritance, it would make it a great alternative to freezed.

**Comment by numen31337** [comment]
Hey @Wishmater, could you take a look at the project tests [here](https://github.com/numen31337/copy_with_extension/blob/master/copy_with_extension_gen/test/gen_inheritance_test.dart). Is there anything missing in your opinion?

**Comment by Wishmater** [comment]
Thank you for your answer. According to that example, it IS possible to do what I want. When I tested it in a more complex case, the fields declared in class A didn't show in class B. I must have done something wrong... It does work if done like in the example.

**Comment by deimantasa** [comment]
@Wishmater - could you share how did you solve it? I'm facing exact same issue and not entirely sure, how to make `super class` method visible in `child class'es` copyWith method.

**Comment by numen31337** [comment]
@deimantasa The library uses the initialiser as a reference and as an entry point to create the class. Since your initialiser only has fields from the second class, this is the only thing it sees. Looks about right to me.

**Comment by deimantasa** [comment]
What would be your suggestion to solve this issue? Keeping the same structure (child + super class).
