### ISSUE TITLE
Add Support for Generic Types

### ISSUE THREAD

**Issue by numen31337** [numen31337/copy_with_extension#5]
In order to make this library completely useable in production codebases, we need to support the Generic Types, the current solution just omits them which makes our codebase less type-safe by employing the `dynamic` type instead.

One of the solutions that I've [already tried](https://github.com/numen31337/copy_with_extension/pull/4) is to use the names of [ClassElement.typeParameters](https://pub.dev/documentation/analyzer/latest/dart_element_element/TypeParameterizedElement/typeParameters.html). Unfortunately, it covers only the simple cases when the `T` is just some basic type. Probably we can follow all the `typeParameters` recursively to extract the full type information.

The solution still has to cover cases like types that `extends` other types as this is also a part of the type annotation.

In order to test everything out one can think of a class which looks like this:
```dart
import 'package:meta/meta.dart' show immutable, required;
import 'package:copy_with_extension/copy_with_extension.dart';

part 'sub_class.g.dart';

abstract class AClass {
  final String aString;

  AClass(this.aString);
}

@immutable
@CopyWith()
class BasicBaseClass {
  final String id;

  BasicBaseClass({this.id});
}

mixin TestMixin on BasicBaseClass {
  String get mixinMethod;
}

@immutable
@CopyWith()
class SubClass<T, U extends String> extends BasicBaseClass
    with TestMixin
    implements AClass {
  final DateTime date;
  final String aString;
  final String privateField;
  static String staticStr;
  final List<T> listWithGenericType;
  final List<Iterable<U>> listWithTypedType;
  final List<int> listWithType;

  SubClass({
    String id,
    @required this.date,
    this.privateField,
    this.aString,
    this.listWithGenericType,
    this.listWithTypedType,
    this.listWithType,
  }) : super(id: id);

  SubClass.secondConstructor({String id})
      : this(id: id, date: DateTime.now(), privateField: "", aString: "");

  factory SubClass.testFactory() {
    return SubClass.secondConstructor(id: "");
  }

  String get testMethod {
    return "test";
  }

  String get mixinMethod {
    return "test";
  }
}
```

**Comment by windrunner414** [comment]
maybe we can use type.bound

**Comment by windrunner414** [comment]
revert to my first commit and try again

**Comment by MisterJimson** [comment]
Just a note that this issue makes this library incompatible with `implicit-casts: false`, as the generic type can not be allowed to default to dynamic.
```
analyzer:	
  strong-mode:	
    implicit-casts: false
```

**Comment by MisterJimson** [comment]
Also, to fix the issue mentioned in my last comment, we could add: 

`// ignore_for_file: argument_type_not_assignable`

To the generated code as a temp workaround.

**Comment by numen31337** [comment]
@MisterJimson thank you for pointing out this issue. I introduced [the temporary fix](https://github.com/numen31337/copy_with_extension/commit/8c285b92ab896506c80acddcdc51556e95f9d275) and updated this library to suppress this warning until it supports the generic types.

**Comment by MisterJimson** [comment]
@numen31337 thanks for the quick fix!

**Comment by numen31337** [comment]
The latest version https://github.com/numen31337/copy_with_extension/releases/tag/1.2.0 introduces support for generic types, please let me know if you experiencing any issues with the new functionality.
