### ISSUE TITLE
generated code should follow the sort_constructors_first lint rule

### ISSUE THREAD

**Issue by LostInDarkMath** [numen31337/copy_with_extension#68]
**Describe the issue**

In the generated `_$FooCWProxyIml` class the constructor comes after the field `final Foo _value;`. But most linters like to follow the [sort_constructor_first lint rule](https://dart-lang.github.io/linter/lints/sort_constructors_first.html).

**Environment details**

Paste the flutter environment detail.
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.5, on Microsoft Windows [Version 6.1.7601], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.10.3)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.70.1)
[√] Connected device (2 available)
[√] HTTP Host Availability

• No issues found!
```

package version:
```
dependencies:
  copy_with_extension: 4.0.4
dev_dependencies:
  copy_with_extension_gen: 4.0.4
```

**Expected behaviour**

Constructor should be above the field in the generated code file.

**Comment by LostInDarkMath** [comment]
Okay, good point. Maybe you include this hint in the documentation as well :)

**Comment by mrgnhnt96** [comment]
@numen31337 (or @LostInDarkMath) this issue can be closed

**Comment by numen31337** [comment]
I'll have a look when I have nothing else to do :)
Changing the order won't hurt, but might make some people happy who want to lint their generated code.
Of course, I agree that this is a purely stylistic decision.
