### ISSUE TITLE
Can't set null to copy

### ISSUE THREAD

**Issue by renanarceno** [numen31337/copy_with_extension#7]
We can't set a copy parameter as null.

Example:

```dart
@CopyWith()
class Test {
  final int foo;
  final String bar;

  Test({this.foo, this.bar});
}

main() {
  test('Nullability test', () {
    Test original = Test(foo: 1, bar: 'Testing');
    Test copy = original.copyWith(foo: null, bar: null);

    expect(copy.foo, isNull);
    expect(copy.bar, isNull);
  });
}
```

> Expected: null 
Actual: <1>

Versions used: 
```
copy_with_extension_gen: ^1.0.7
copy_with_extension: ^1.0.7
```

**Comment by MisterJimson** [comment]
This is a problem with standard copyWith implementations as well. You can't tell the difference between null and nothing passed in.

An idea could be to generate a `nullX` for every field, that would do this.

`original.copyWith(nullFoo: true, nullBar: true);`

So you would use copyWith as normal, but when you really want to clear something you cam with this alternative syntax.

**Comment by numen31337** [comment]
@renanarceno, as @MisterJimson already said, that's how `copyWith` approach works. There could be another solution, we can introduce an additional function say `original.copyWithNulls(nullFoo: true)`. I would personally wait until the nullable types will be officially introduced, I believe it will resolve the issues and allow us to deal with this in some meaningful way.

**Comment by MisterJimson** [comment]
@numen31337 one thing to think about is that the new nullable support will be optional and opt in for a long time. May want support for a way to null fields for users who choose not to use it, or start using it way later.

**Comment by numen31337** [comment]
> @numen31337 one thing to think about is that the new nullable support will be optional and opt in for a long time. May want support for a way to null fields for users who choose not to use it, or start using it way later.

Fair point, it is still unclear how this migration will be implemented.

**Comment by numen31337** [comment]
Introduced in [version 1.1.0](https://github.com/numen31337/copy_with_extension/releases/tag/1.1.0).
Special thanks to @JuanM04.
