### ISSUE TITLE
Avoid including constructor parameters that are not fields.

### ISSUE THREAD

**Issue by luis901101** [numen31337/copy_with_extension#73]
**Describe the issue**
If I have an ephemeral parameter in constructor that is to be used for field initialization, it should not be taken into account as a **copyWith** field.

**Paste the package version.**
```yaml
dependencies:
  copy_with_extension: ^5.0.0
dev_dependencies:
  copy_with_extension_gen: ^5.0.0
```

**To Reproduce**
Steps to reproduce the behaviour:
```dart
import 'package:copy_with_extension/copy_with_extension.dart';

part 'test.g.dart';

@CopyWith()
class Test {
  static const defaultDomainUrl = 'https://my.default.url.com';

  String id;
  String thumbnail;
  String playbackUrl;

  Test({
    String? nullableId,
    String? thumbnail,
    String? playbackUrl,
    String? customAccountSubdomainUrl,
  })  : id = nullableId ??= '123',
        thumbnail = thumbnail ??
            (nullableId.isNotEmpty
                ? '${customAccountSubdomainUrl ?? defaultDomainUrl}/$nullableId/thumbnails/thumbnail.jpg'
                : ''),
        playbackUrl = playbackUrl ??
            (nullableId.isNotEmpty
                ? '${customAccountSubdomainUrl ?? defaultDomainUrl}/$nullableId/playback.hls'
                : '');
}
```
Generated code references `nullableId` and `customAccountSubdomainUrl` as class fields which is wrong.
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'test.dart';

// **************************************************************************
// CopyWithGenerator
// **************************************************************************

abstract class _$TestCWProxy {
  Test nullableId(String? nullableId);

  Test thumbnail(String? thumbnail);

  Test playbackUrl(String? playbackUrl);

  Test customAccountSubdomainUrl(String? customAccountSubdomainUrl);

  /// This function **does support** nullification of nullable fields. All `null` values passed to `non-nullable` fields will be ignored. You can also use `Test(...).copyWith.fieldName(...)` to override fields one at a time with nullification support.
  ///
  /// Usage
  /// ```dart
  /// Test(...).copyWith(id: 12, name: "My name")
  /// ````
  Test call({
    String? nullableId,
    String? thumbnail,
    String? playbackUrl,
    String? customAccountSubdomainUrl,
  });
}

/// Proxy class for `copyWith` functionality. This is a callable class and can be used as follows: `instanceOfTest.copyWith(...)`. Additionally contains functions for specific fields e.g. `instanceOfTest.copyWith.fieldName(...)`
class _$TestCWProxyImpl implements _$TestCWProxy {
  const _$TestCWProxyImpl(this._value);

  final Test _value;

  @override
  Test nullableId(String? nullableId) => this(nullableId: nullableId);

  @override
  Test thumbnail(String? thumbnail) => this(thumbnail: thumbnail);

  @override
  Test playbackUrl(String? playbackUrl) => this(playbackUrl: playbackUrl);

  @override
  Test customAccountSubdomainUrl(String? customAccountSubdomainUrl) =>
      this(customAccountSubdomainUrl: customAccountSubdomainUrl);

  @override

  /// This function **does support** nullification of nullable fields. All `null` values passed to `non-nullable` fields will be ignored. You can also use `Test(...).copyWith.fieldName(...)` to override fields one at a time with nullification support.
  ///
  /// Usage
  /// ```dart
  /// Test(...).copyWith(id: 12, name: "My name")
  /// ````
  Test call({
    Object? nullableId = const $CopyWithPlaceholder(),
    Object? thumbnail = const $CopyWithPlaceholder(),
    Object? playbackUrl = const $CopyWithPlaceholder(),
    Object? customAccountSubdomainUrl = const $CopyWithPlaceholder(),
  }) {
    return Test(
      nullableId: nullableId == const $CopyWithPlaceholder()
          ? _value.nullableId
          // ignore: cast_nullable_to_non_nullable
          : nullableId as String?,
      thumbnail: thumbnail == const $CopyWithPlaceholder()
          ? _value.thumbnail
          // ignore: cast_nullable_to_non_nullable
          : thumbnail as String?,
      playbackUrl: playbackUrl == const $CopyWithPlaceholder()
          ? _value.playbackUrl
          // ignore: cast_nullable_to_non_nullable
          : playbackUrl as String?,
      customAccountSubdomainUrl:
          customAccountSubdomainUrl == const $CopyWithPlaceholder()
              ? _value.customAccountSubdomainUrl
              // ignore: cast_nullable_to_non_nullable
              : customAccountSubdomainUrl as String?,
    );
  }
}

extension $TestCopyWith on Test {
  /// Returns a callable class that can be used as follows: `instanceOfTest.copyWith(...)` or like so:`instanceOfTest.copyWith.fieldName(...)`.
  // ignore: library_private_types_in_public_api
  _$TestCWProxy get copyWith => _$TestCWProxyImpl(this);
}

```

**Expected behaviour**
Generated code don’t use ephemeral constructor params... maybe this could be done by defining some @Annotation for params to allow to ignore some params, or just set param ignoring existing param I mean something like:

```dart
 return Test(
      nullableId: nullableId as String?,
      thumbnail: thumbnail == const $CopyWithPlaceholder()
          ? _value.thumbnail
          // ignore: cast_nullable_to_non_nullable
          : thumbnail as String?,
      playbackUrl: playbackUrl == const $CopyWithPlaceholder()
          ? _value.playbackUrl
          // ignore: cast_nullable_to_non_nullable
          : playbackUrl as String?,
      customAccountSubdomainUrl: customAccountSubdomainUrl as String?,
    );
```

**Comment by numen31337** [comment]
Hm, I'm not quite sure how to solve this problem, but it feels like the solution is full of pitfalls, as the fields in the constructor might conflict or have some not-so-obvious behaviour. Personally, I would recommend having a designated constructor that initialises fields with raw data, and have these types of constructors as named, special purpose ones.

**Comment by numen31337** [comment]
I have recently worked on topic of default values in constructors [here](https://github.com/numen31337/copy_with_extension/issues/79) and [here](https://github.com/numen31337/copy_with_extension/pull/78). The current behaviour of the library will indeed result in having ephemeral and any other parameters, such as fallbacks and side-effects, which are not always desirable. The issue is that the library uses predefined constructors, and it is currently impossible to define/generate additional constructors in extensions to only include class fields. In order to overcome this issue, I suggest creating an additional constructor (can be private) that includes class fields instead of relying on the constructor in example, as this will help avoid any related issues.

The topic at hand is centred around introducing a new type of behaviour by generating class field constructors, rather than reusing the existing ones. This approach is similar to how the [freezed](https://pub.dev/packages/freezed) library operates, which may be a better fit for this situation since it generates everything.

**Comment by luis901101** [comment]
Understood, I just was expecting maybe the  `copy_with_extension_gen` could generate code similar to `json_serializable` which handles this case as expected, I mean it doesn`t consider constructor level fields as class fields.

**Comment by numen31337** [comment]
@luis901101 I looked at `json_serializable` using the provided example and found that it indeed populates only class fields and sets the `id` field on the created object, while still reusing the provided constructor. However, if the `id` field is marked as `final`, like in more real-world case scenario, it is using initializer's fallback and ignores the field completely. This approach has its own set of risks, as we can see here, so I'm not entirely convinced that it is better. I believe that having a private constructor for scenarios like `json_serializable` and `copyWith` is a more appropriate solution.

Here the generated code with `final id` which is clearly incorrect as we ignore `id` from a JSON here completely.
```dart
Test _$TestFromJson(Map<String, dynamic> json) => Test(
      thumbnail: json['thumbnail'] as String?,
      playbackUrl: json['playbackUrl'] as String?,
    );
```
