### ISSUE TITLE
Add "// coverage:ignore-file" to each generated file

### ISSUE THREAD

**Issue by exbrain-dev** [numen31337/copy_with_extension#77]
Coverage reports include generated files, which is generally unwanted. The addition of `// coverage:ignore-file` causes files to be ignored.
Adding this should be a relatively simple change, but perhaps there could also be a setting somehow to turn coverage on if it's wanted.

**Comment by zeshuaro** [comment]
Just dropping this down here, you can also use the `remove_from_coverage` [package](https://pub.dev/packages/remove_from_coverage) to ignore coverage for certain file patterns.

**Comment by numen31337** [comment]
Hello @exbrain-dev, I appreciate your request. However, I do not believe it is advisable to proceed with it. The reason being, this library shares the generated file with other libraries like JsonSerializable, which means that the library would have to imply certain behaviours that it doesn't control. The key feature of this library, compared to freezed, is to be minimally invasive. Therefore, I recommend following @zeshuaro's suggestion and excluding the generated files in the tool configuration, which is a common practice for dealing with analysers.
