### ISSUE TITLE
InvalidType for Enum type

### ISSUE THREAD

**Issue by chutuananh2k** [numen31337/copy_with_extension#91]
The generated file generate `InvalidType` for `TextDirection` which is an enum.

```
@CopyWith()
class AppThemeData {
  // ...
  final TextDirection? textDirection;
  const AppThemeData({
    this.textDirection
  });

  AppThemeData.Default()
      :  textDirection = TextDirection.ltr;
}
```

**Comment by Ali1Ammar** [comment]
in my code TextStyle is converted to InvalidType for unknown reason , while TextDirection is converted correctly , 
I think there is change at flutter or analyzer package which case this as It was working before

**Comment by Ali1Ammar** [comment]
for unknown reason after some re-generate the error is gone

**Comment by numen31337** [comment]
I’ve tested both cases you mentioned, but unfortunately, I can’t reproduce the issue. Please reopen the issue if you have more details about it.

**Comment by BenjiFarquhar** [comment]
I have this error for an enum that is imported from a third party package. Guessing code gen would struggle with enums from other packages?

**Comment by numen31337** [comment]
Hey @BenjiFarquhar. Can you give a reproducible example?
